### PR TITLE
Add `material` spinner

### PR DESCRIPTION
**Pull request by Richienb**
cc @sindresorhus

### CODE REVIEW

**Comment by sindresorhus** [comment]
Close, but any chance you can make it more fluid?

Look at the spinner in https://material.io/components/progress-indicators#linear-progress-indicators. It changes size.

**Comment by Richienb** [comment]
@sindresorhus How many characters long should the spinner be?

**Comment by sindresorhus** [comment]
Not more than 20.

**Comment by Richienb** [comment]
@sindresorhus I've just eyeballed the entire animation at 60fps. It should be fluid enough now.

**Comment by sindresorhus** [comment]
Almost. The material loader seems to stretch on the first line, and on the second round it shrinks. I only see the latter here.

**Comment by Richienb** [comment]
@sindresorhus You've just described the correct result - try rewatching the original animation.

**Comment by sindresorhus** [comment]
I saw it. I just think the stretching could be done in a couple of fewer frames so it's more visible.

**Comment by Richienb** [comment]
@sindresorhus The stretching time is exactly the same as the original - I wouldn't know how to make it faster without breaking the spec.

Spinner Comparison

**Comment by sindresorhus** [comment]
I have been watching both my terminal and your GIF and it's pretty clear to me that it doesn't stretch as much as in the original material spinner.

I would start the spinner a tiny bit smaller, so the stretch is more clear.

**Comment by sindresorhus** [comment]
Bump

**Comment by Richienb** [comment]
@sindresorhus 

> I just think the stretching could be done in a couple of fewer frames so it's more visible.

Done.

**Pull request merged**
