### PR TITLE
feat: added binary variant

### PR DESCRIPTION
**Pull request by ad4mx**
Hello, I've added a binary variant which flashes random strings of binary.

### CODE REVIEW

**Comment by sindresorhus** [comment]
It feels a little bit too fast and too repetitive. I would include some more random permutations.

**Comment by mainrs** [comment]
> It feels a little bit too fast and too repetitive. I would include some more random permutations.

Maybe suffixing them with the number of bits they use could be a good idea as well. `binary6` in this case. It would ensure that additional binary spinners have a common naming scheme.

**Comment by sindresorhus** [comment]
> Maybe suffixing them with the number of bits they use could be a good idea as well. binary6 in this case. It would ensure that additional binary spinners have a common naming scheme.

I don't think that's necessary. I don't want to encourage a lot of binary spinners. There are endless permutations.

**Comment by sindresorhus** [comment]
Bump :)

**Comment by ad4mx** [comment]
Hi, sorry for the inactivity - I forgot about this. Anyways, I slowed the spinner down and added more permutations to the binary numbers.

**Pull request merged**
