### PR TITLE
Allow user to skip spinner (#4)

### PR DESCRIPTION
**Pull request by gliluaume**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Why did you close?

**Comment by gliluaume** [comment]
Because it broke tests. I made a cleaner PR https://github.com/sindresorhus/cli-spinners/pull/27

**Comment by sindresorhus** [comment]
Next time, just push updates to the existing PR instead. There's never any need to open a new PR ;)

**Comment by gliluaume** [comment]
Ok

**Pull request closed without merging**
