### PR TITLE
Request to enhance the windowsify spinner (dots12)

### PR DESCRIPTION
**Pull request by AozakiOrenji**
by adding some empty copied from the 1st frame to the end of the list

### CODE REVIEW

**Comment by sindresorhus** [comment]
Why? How does this make it better?

**Comment by AozakiOrenji** [comment]
Real windows spinner has a interval after 2 times spin(but most of refact version forgot this). I just added this interval to make it more like windows loading spinner.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by SamVerschueren** [comment]
If we want to add this, we should give it a new name, `windows` or something.

**Comment by AozakiOrenji** [comment]
@SamVerschueren dots12 was similar to windows spinner but not was that...?

**Comment by AozakiOrenji** [comment]
@sindresorhus Sorry, that's an error. I downloaded the Windows 8 consumer preview x86 and I see the spinner has no interval.

**Pull request closed without merging**
