### PR TITLE
Add `dots8Bit` spinner

### PR DESCRIPTION
**Pull request by casey**
The frames are ordered to represent the 8 bit numbers in increasing
order. The individual braille cells represent bits, with empty cells
representing `0` and full cells representing `1`.

Digits are ordered from least significant to most significant from
top to bottom, and then left to right, like so:

    ╔═════╗
    ║ 0 4 ║
    ║ 1 5 ║
    ║ 2 6 ║
    ║ 3 7 ║
    ╚═════╝

### CODE REVIEW

**Comment by sindresorhus** [comment]
Can you name it something more descriptive? Maybe `dots-8bit` or `dots-binary`.

**Comment by casey** [comment]
Done! I renamed it `dots-8bit`.

**Comment by sindresorhus** [comment]
Actually, the name needs to be in camel-case.

**Comment by casey** [comment]
Update, now it's `dots8Bit`

**Comment by sindresorhus** [comment]
You need to add it to https://github.com/sindresorhus/cli-spinners/blob/master/index.d.ts too

**Comment by casey** [comment]
Added!

**Pull request merged**
