### PR TITLE
Add one line Pong loader

### LINKED ISSUE #5: Multi-line pong loader
Would it be possible to have a pong loader ? Something on multiple lines probably

This should be easy to represent in ASCII. I don't think that we need the scores, just the ball bouncing off from left to right to left., and not in a straight line, but moving like it is moving in pong (up, down, ...).

It would probably look like "bouncingBall" but on multiple lines, with a few different patterns to make it look like a "real" pong game.

### PR DESCRIPTION
**Pull request by zckrs**
cli-spinners-pong

ping @ocombe

### CODE REVIEW

**Comment by bojidar-bg** [comment]
Maybe you can make some paddles too? :smile:

**Comment by sindresorhus** [comment]
This one looks good and I'll include it, but I don't think it completely resolves #5, which is more ambitious.

**Comment by sindresorhus** [comment]
> Maybe you can make some paddles too?

For that to work it would need to be multiline and better fixed in a separate spinner as commented above.

**Comment by zckrs** [comment]
Agree this not completely resolves issue.

I imagine a more ambitious PONG loader with https://github.com/sindresorhus/boxen and more patterns

**Pull request closed without merging**
